version: "3.8"
services:
  postgres:
    image: postgres:13.4-alpine
    container_name: keycloak_postgres
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak1234~
    ports:
    - 15432:5432
  keycloak:
    image: bitnami/keycloak:14.0.0
    depends_on:
    - postgres        
    container_name: keycloak
    #        restart: always
    environment:
    - KEYCLOAK_ENABLE_STATISTICS=true
    - KEYCLOAK_ADMIN_USER=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin
    - KEYCLOAK_DATABASE_HOST=postgres
    - KEYCLOAK_DATABASE_PORT=5432
    - KEYCLOAK_DATABASE_NAME=keycloak
    - KEYCLOAK_DATABASE_USER=keycloak
    - KEYCLOAK_DATABASE_PASSWORD=keycloak1234~
    - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.scripts=enabled
    - KEYCLOAK_LOG_LEVEL=INFO
    - KEYCLOAK_ROOT_LOG_LEVEL=INFO
    ports:
    - "63333:8080"
    expose:
    - 8080
    volumes:
    - ./themes/ndc-ui:/opt/bitnami/keycloak/themes/ndc-ui
    - ./deployments:/opt/bitnami/keycloak/standalone/deployments
  nginx:
    image: nginx:1.21.5-alpine
    depends_on:
    - keycloak
    container_name: keycloak_nginx
    ports:
    - 33333:8080
    - 33334:8081
    volumes:
    - ./conf:/etc/nginx/conf.d
    - ./logs:/logs


