version: "3.8"
services:
  postgres:
    image: postgres:13.4-alpine
    container_name: pgdb
    #restart: always
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234~
    ports:
    - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:6.5
    container_name: pgadmin4
    depends_on:
    - postgres  
    #restart: always
    ports:
    - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: kai.kang@nexr.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin