version: "3.8"
services:
  redis: 
    image: bitnami/redis:6.2.6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD="redis1234~"
      - REDIS_ACLFILE=/opt/bitnami/redis/mounted-etc/users.acl
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./acl/users.acl:/opt/bitnami/redis/mounted-etc/users.acl
      - ./conf/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf
      - /docker/redis/data:/bitnami/redis/data
